spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/food_delivery"
    username: "root"
    password: "admin123"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources: # Static resources
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

  mail:
    host: smtp.gmail.com
    username: fooddeliveryyyy@gmail.com
    password: vvnkieadnhypxfci
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
    upload-dir: food_project\src\main\resources\static\img




